spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/blog_microservice_comment?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQLDialect



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://User:e8cbe34f-1e0c-48e1-be15-b2c8bbc779a7@localhost:8761/eureka





# Spring profile (uncomment if needed)
# spring:
#   profiles:
#     active: dev
